# Nightshade Start - BSO Chester set
- type: entity
  parent: BlueshieldAmmunitionBox
  id: BlueshieldAmmunitionBoxFilled
  suffix: Filled
  components:
  - type: StorageFill
    contents:
    - id: MagazineBoxMagnum
    - id: MagazineBoxMagnumEnsnaring
    - id: MagazineBoxMagnumFlash
    # - id: MagazineBoxMagnumEMP
    - id: MagazineMagnumLeverRifleEmpty
      amount: 2
# Nightshade End
